#!/bin/bash

#script to add phone carries to master list
#KM4ACK 02AUGUST2022

FILE=$HOME/patmenu2/sms/cellproviders.txt
MYTEMP=/run/user/$UID/templist.txt
MAIN=$HOME/patmenu2/sms/manage-sms

INFO=$(PARSER='OFS="\n" {print $1}'

tail -300 $FILE | awk "$PARSER" | \
yad --title="Search Results" --width=1100 --height=500 \
    --image $LOGO --window-icon=$LOGO --image-on-top --multiple \
    --center --list --text="Carrier List" \
    --column Carrier \
    --button=gtk-close \
    --button="Add Carrier":2 > $MYTEMP)
BUT=$?
sed -i 's/|//g' $MYTEMP

cat $MYTEMP >> $HOME/patmenu2/sms/myphonelist.txt
sort $HOME/patmenu2/sms/myphonelist.txt > /run/usr/$UID/sortedlist
mv /run/user/$UID/sortedlist $HOME/patmenu2/sms/myphonelist.txt

yad --center --timeout=3 --timeout-indicator=top --no-buttons --text="The carrier list has been updated"

$MAIN &
exit