#!/bin/bash

MYPATH=$HOME/patmenu2
LOGO=$MYPATH/pmlogo.png
source $MYPATH/manage-pat-functions
MAIN=$MYPATH/patmenu


yad --form --width=420 --text-align=center --center --title="Manage Pat" --text-align=center \
--image $LOGO --window-icon=$LOGO --image-on-top --separator="|" --item-separator="|" \
--text="<b>Manage Pat</b> by KM4ACK" \
--field="Pat Login-Logout":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; LOGIN"' \
--field="GPS Grid Update":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; GPSGRID"' \
--field="Set ARDOP Speed":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; SPEED"' \
--field="Delete Alias":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; DELETEALIAS"' \
--field="Backup Emails":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; EMAILBKUP"' \
--field="Restore Emails":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; EMAILRESTORE"' \
--field="Backup Pat Config":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; BKUPCONFIG"' \
--field="Restore Pat Config":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/manage-pat-functions; RESTORECONFIG"' \
--button="Main Menu":1
BUT=$?

if [ $BUT = 1 ]; then
$MAIN &
exit
fi

echo $?