#!/bin/bash

#install script patmenu2
#20200511 km4ack


MYPATH=$HOME/patmenu2
BKDIR=$HOME/Desktop/config-bkups
NEWCONFIG=$HOME/Desktop/test.txt

#get depends if needed.
sudo apt-get update
if ! hash yad 2>/dev/null; then
sudo apt install -y yad
fi
if ! hash jq 2>/dev/null; then
sudo apt install -y jq
fi

if [ -f $HOME/patmenu/config ]; then
#get patmenu config file and copy to patmenu2
cp $HOME/patmenu/config $HOME/patmenu2/config

#create backup folder and copy any user config files from patmenu1
mkdir -p $BKDIR
cp $HOME/patmenu/*config* $BKDIR
#remove restore script that gets copied with above command
rm $BKDIR/restore-config

#remove old patmenu
rm -rf $HOME/patmenu

	#remove old shortcut if exist
	if [ -L $HOME/Desktop/Pat-Menu ]; then
	rm $HOME/Desktop/Pat-Menu
	fi

fi


#create new desktop link
cat <<EOF > /run/user/$UID/patmenu.desktop
[Desktop Entry]
Name=Pat Menu
GenericName=Amateur Radio Digital Modem
Comment=Amateur Radio Sound Card Communications
Exec=/home/`whoami`/patmenu2/patmenu
Icon=/home/`whoami`/patmenu2/pmlogo.png
Terminal=false
Type=Application
Categories=Network;HamRadio;
EOF
sudo cp /run/user/$UID/patmenu.desktop /usr/share/applications/patmenu.desktop

#download RMS List
$MYPATH/getardoplist

#remove this script
rm $MYPATH/setup

