#!/bin/bash

#install script patmenu2
#20200511 km4ack


MYPATH=$HOME/patmenu2
BKDIR=$HOME/Desktop/config-bkups
NEWCONFIG=$HOME/Desktop/test.txt

if [ -f $HOME/patmenu/config ]; then
#get patmenu config file and copy to patmenu2
cp $HOME/patmenu/config $HOME/patmenu2/config

#create backup folder and copy any user config files from patmenu1
mkdir -p $BKDIR
cp $HOME/patmenu/*config* $BKDIR
#remove restore script that gets copied with above command
rm $BKDIR/restore-config

#remove old patmenu
rm -rf $HOME/patmenu

	#remove old shortcut if exist
	if [ -L $HOME/Desktop/Pat-Menu ]; then
	rm $HOME/Desktop/Pat-Menu
	fi

fi


#copy new desktop link 
sudo cp $MYPATH/patmenu2.desktop /usr/share/applications/patmenu.desktop

#download RMS List
$MYPATH/getardoplist

#remove this script
rm $MYPATH/setup

