#!/bin/bash

#20191117 km4ack

MYPATH=$HOME/patmenu2
LOGO=$MYPATH/pmlogo.png

#stop all modems that might be running

sudo killall direwolf piardopc kissattach piARDOP_GUI > /dev/null 2>&1

yad --title="Modem Stopped" --width=400 --height=100 \
    --image $LOGO --window-icon=$LOGO --image-on-top --text-align=center \
    --center --form --text="\r\r\rModem has been stopped" \
    --button=gtk-ok

sleep 2

exit 0
